/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CrateWorkflowStatusDetails : The details of a transition status.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CrateWorkflowStatusDetails {
    /// The ID of the status.
    #[serde(rename = "id")]
    pub id: String,
}

impl CrateWorkflowStatusDetails {
    /// The details of a transition status.
    pub fn new(id: String) -> CrateWorkflowStatusDetails {
        CrateWorkflowStatusDetails {
            id,
        }
    }
}

