/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CustomFieldContextDefaultValue {
    #[serde(rename="option.cascading")]
    OptionPeriodCascading(Box<models::CustomFieldContextDefaultValueCascadingOption>),
    #[serde(rename="option.multiple")]
    OptionPeriodMultiple(Box<models::CustomFieldContextDefaultValueMultipleOption>),
    #[serde(rename="option.single")]
    OptionPeriodSingle(Box<models::CustomFieldContextDefaultValueSingleOption>),
}

impl Default for CustomFieldContextDefaultValue {
    fn default() -> Self {
        Self::OptionPeriodCascading(Default::default())
    }
}


