/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IssueLink : Details of a link between issues.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssueLink {
    /// The ID of the issue link.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The URL of the issue link.
    #[serde(rename = "self", skip_serializing_if = "Option::is_none")]
    pub param_self: Option<String>,
    /// The type of link between the issues.
    #[serde(rename = "type")]
    pub r#type: Box<models::IssueLinkType>,
    /// The issue the link joins to.
    #[serde(rename = "inwardIssue")]
    pub inward_issue: Box<models::LinkedIssue>,
    /// The issue the link originates from.
    #[serde(rename = "outwardIssue")]
    pub outward_issue: Box<models::LinkedIssue>,
}

impl IssueLink {
    /// Details of a link between issues.
    pub fn new(r#type: models::IssueLinkType, inward_issue: models::LinkedIssue, outward_issue: models::LinkedIssue) -> IssueLink {
        IssueLink {
            id: None,
            param_self: None,
            r#type: Box::new(r#type),
            inward_issue: Box::new(inward_issue),
            outward_issue: Box::new(outward_issue),
        }
    }
}

