/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectIdentifiers : Identifiers for a project.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectIdentifiers {
    /// The URL of the created project.
    #[serde(rename = "self")]
    pub param_self: String,
    /// The ID of the created project.
    #[serde(rename = "id")]
    pub id: i64,
    /// The key of the created project.
    #[serde(rename = "key")]
    pub key: String,
}

impl ProjectIdentifiers {
    /// Identifiers for a project.
    pub fn new(param_self: String, id: i64, key: String) -> ProjectIdentifiers {
        ProjectIdentifiers {
            param_self,
            id,
            key,
        }
    }
}

