/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowConditionBean : The workflow conditions tree.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "nodeType")]
pub enum WorkflowConditionBean {
    #[serde(rename="simple")]
    Simple(Box<models::WorkflowSimpleCondition>),
    #[serde(rename="compound")]
    Compound(Box<models::WorkflowCompoundCondition>),
}

impl Default for WorkflowConditionBean {
    fn default() -> Self {
        Self::Simple(Default::default())
    }
}

/// The conditions operator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "AND")]
    And,
    #[serde(rename = "OR")]
    Or,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::And
    }
}

