/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowCompoundCondition : A workflow transition compound condition rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowCompoundCondition {
    /// The conditions operator.
    #[serde(rename = "operator")]
    pub operator: Operator,
    /// The list of workflow conditions.
    #[serde(rename = "conditions")]
    pub conditions: Vec<models::WorkflowConditionBean>,
    #[serde(rename = "nodeType")]
    pub node_type: String,
}

impl WorkflowCompoundCondition {
    /// A workflow transition compound condition rule.
    pub fn new(operator: Operator, conditions: Vec<models::WorkflowConditionBean>, node_type: String) -> WorkflowCompoundCondition {
        WorkflowCompoundCondition {
            operator,
            conditions,
            node_type,
        }
    }
}
/// The conditions operator.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "AND")]
    And,
    #[serde(rename = "OR")]
    Or,
}

impl Default for Operator {
    fn default() -> Operator {
        Self::And
    }
}

