/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WorkflowTransitionRule : A workflow transition rule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowTransitionRule {
    /// The type of the transition rule.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The configuration of the transition rule. This is currently returned only for some of the rule types. Availability of this property is subject to change.
    #[serde(rename = "configuration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<Option<serde_json::Value>>,
}

impl WorkflowTransitionRule {
    /// A workflow transition rule.
    pub fn new(r#type: String) -> WorkflowTransitionRule {
        WorkflowTransitionRule {
            r#type,
            configuration: None,
        }
    }
}

